swagger: "2.0"
info:
  description: "T"
  version: "1.0.0"
  title: "Swagger Petstore"
host: "petstore.swagger.io"
basePath: "/v1"
tags:
  - name: "tokens"
  - name: "me"
  - name: "companies"
schemes:
  - "https"
  - "http"
paths:
  /me:
    get:
      tags:
        - "me"
      summary: "Information related to the authenticated user"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters: ~
      security:
        - bearer: []
      x-slim-action: Ergosense\Action\Me
  /tokens:
    post:
      tags:
        - "tokens"
      summary: "Generate a new access token"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Pet object that needs to be added to the store"
          required: true
          schema:
            $ref: "#/definitions/Pet"
      responses:
        405:
          description: "Invalid input"
      security: ~
      x-slim-action: Ergosense\Action\CreateToken
  /companies:
    get:
      tags:
        - companies
      summary: ""
      consumes:
        - application/json
      produces:
        - application/json
      security:
        - bearer: []
      x-slim-action: Ergosense\Action\Company\Search
  /companies/{companyId}:
    get:
      tags:
        - companies
      summary: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: companyId
          schema:
            type: integer
          required: true
      security:
        - bearer: []
      x-slim-action: Ergosense\Action\Company\Get
securityDefinitions:
  bearer:
    type: "http"
    scheme: "bearer"
    bearerFormat: "JWT"
definitions:
  Order:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      petId:
        type: "integer"
        format: "int64"
      quantity:
        type: "integer"
        format: "int32"
      shipDate:
        type: "string"
        format: "date-time"
      status:
        type: "string"
        description: "Order Status"
        enum:
        - "placed"
        - "approved"
        - "delivered"
      complete:
        type: "boolean"
        default: false
    xml:
      name: "Order"
  Category:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Category"
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      phone:
        type: "string"
      userStatus:
        type: "integer"
        format: "int32"
        description: "User Status"
    xml:
      name: "User"
  Tag:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Tag"
  Pet:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      id:
        type: "integer"
        format: "int64"
      category:
        $ref: "#/definitions/Category"
      name:
        type: "string"
        example: "doggie"
      photoUrls:
        type: "array"
        xml:
          name: "photoUrl"
          wrapped: true
        items:
          type: "string"
      tags:
        type: "array"
        xml:
          name: "tag"
          wrapped: true
        items:
          $ref: "#/definitions/Tag"
      status:
        type: "string"
        description: "pet status in the store"
        enum:
        - "available"
        - "pending"
        - "sold"
    xml:
      name: "Pet"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"